name: MLB Scorigami Data Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  update-mlb-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- START NEW DEBUGGING STEP ----
      - name: List files in repository root
        run: ls -la
      # ---- END NEW DEBUGGING STEP ----

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # This is where it fails

      - name: Run MLB Scorigami script
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: python fetch_daily_gamelogs.py # Make sure this is your script name

      - name: Upload Gamelogs CSV as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mlb-gamelogs-csv
          path: outputs/mlb_franchise_gamelogs.csv
          retention-days: 7